---
- name: install redshift
  apt:
    name: redshift-gtk
    update_cache: yes
    cache_valid_time: 3600
  sudo: yes

- name: make sure autostart directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory
    mode: 0755

- name: setup autostart
  copy:
    dest: "{{ ansible_env.HOME }}/.config/autostart/redshift-gtk.desktop"
    src: redshift-gtk.desktop
    force: no
    mode: 0755
