---
- name: YCM dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - build-essential
    - cmake
    - python-dev
  sudo: yes

- name: recompile YCM
  command: "{{ ansible_env.HOME }}/.vim/bundle/YouCompleteMe/install.sh"
  when: updatedYCM|changed
